### PR TITLE
Godeps,vendor: Cleanup/upgrade godeps and migrate to 1.7 vendoring

### PR DESCRIPTION
**Pull request by dseevr**
- updates many out-of-date dependencies (logrus, etcd which was at 2.3.0, etc.)
- removes deprecated (and unsupported as of Go 1.8) `_workspace` directory
- updates Travis CI config so tests actually run and pass
- cleaned up Makefile

Related to: https://github.com/contiv/objdb/pull/20

This PR must be merged AFTER the objdb PR.

objdb + modelgen changes have been tested with netplugin (rev: 8865f9) and are passing

I'll submit a separate PR to update netplugin's Godeps once these two PRs are merged.

### CODE REVIEW

**Comment by erikh** [comment]
did you test this with netplugin?

**Comment by erikh** [comment]
reason I'm asking is that godeps doesn't always work well across multiple repos with godeps in them.

**Comment by dseevr** [comment]
@erikh I'm actually not sure what's required to fully test this... I just saw (while browsing code from this repo) that it had a legacy `_workspace` directory clogging my find-in-repo results, so I ran the restore, rm, and save steps here and pushed a PR to see if it would pass 😄

**Comment by erikh** [comment]
seems good. you might want to merge in the travis PR I just merged and run that. Otherwise, it compiles and passes tests on travis so I think we're good

**Comment by dseevr** [comment]
Rebased on your changes and force pushed and it's passing on 1.6 and 1.7

**Comment by rhim** [comment]
@dseevr this still needed, right?

**Review by rhim — COMMENTED** [review]
Looks like mostly autogen, so good.

**Pull request merged**
